services:
  steamcmd:
    image: awooooool/yasin
    build: .
    volumes:
      - ./serverconfig.xml:/7daystodie/serverconfig.xml
      - ./saves:/root/.local/share/7DaysToDie/Saves
      - ./script/startserver.sh:/7daystodie/startserver.sh
      - ./logs:/7daystodie/7DaysToDieServer_Data/Logs
    ports:
      - 26900:26900/tcp
      - 26900-26903:26900-26903/udp